coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto

ignore:
  - "Tests/**"

comment:
  layout: "reach,diff,flags,files"
  behavior: default
